### ISSUE TITLE
Posters are missing on restarts

### ISSUE THREAD

**Issue by jaketame** [linuxserver/docker-watcher#1]
Posters get overwritten as they are stored under the /app path on restarts on the container

New volume required

- /path/for/posters:/app/watcher/static/images/posters

**Comment by nemchik** [comment]
Could this be reopened?

Reference https://github.com/GhostWriters/DockSTARTer/issues/212

I believe `/app/watcher/userdata` folder and possibly other folders such as the mentioned `/app/watcher/static/images/posters` maybe should be configured by the container to use the `/config` folder. In the very least if this is not done then the readme should note which volumes are needed to use the app without losing data.

**Comment by CHBMB** [comment]
@nemchik We've never released it.  IIRC I approached the dev about some changes to facilitate a docker environment and he wasn't too receptive at the time.  So we stopped working on it.
[
The readme says exactly what it should say.  ](https://github.com/linuxserver/docker-watcher#this-is-a-container-in-active-development-by-the-linuxserverio-team-and-is-not-recommended-for-use-by-the-general-public)

**Comment by nemchik** [comment]
Understood. I was unaware that development had been halted. I will take this into consideration and certainly not use any additional unreleased images in DS in the future. I will also consider if the best route for DS to resolve the issue on my repo is to remove this app entirely or to seek another image (although if the dev of the app was unreceptive to you reaching out then I doubt there will be a better image).

**Comment by nemchik** [comment]
Also FYI the dev of Watcher seems to have included this page in his wiki https://github.com/nosmokingbandit/Watcher3/wiki/Docker-Compose-Example where it seems they are referencing your image. Doesn't change much!

**Comment by CHBMB** [comment]
Well the way they have mapped the volumes would probably solve your issues to be honest.
