### ISSUE TITLE
NZBGet endless fetching

### ISSUE THREAD

**Issue by JoeStratton** [linuxserver/docker-watcher#3]
When Watcher passes the URL format to NZBGet from NZBHydra it sits on "fetching" for about 5 minutes before timing out.

URL format received: http://192.168.1.X:5075/nzbhydra/getnzb?apikey=XXXXXXXXXXXXXXXXXX&searchresultid=c3a0e0fff225df2e30bea05806abf13a46df1db0

Error received (from nzbget): Connection to 192.168.1.X failed: ErrNo 110, Connection timed out

I know this is not NZBGet or NZBHydra's fault because they are both working fine for Sonarr and the original Couchpotato. It is only when Watcher uses NZBHydra that the failure occurs.

There are no proxy's involved.

Attached are the logs with my API key removed.

This was originally opened on the project page itself, but the dev stated that it is a container-specific issue.

Link to issue: https://github.com/nosmokingbandit/watcher/issues/95

[log (2).zip](https://github.com/linuxserver/docker-watcher/files/691591/log.zip)

**Comment by JoeStratton** [comment]
I see, I know its in development, that is why I reported the bug. Thanks for the hard work.

**Comment by sparklyballs** [comment]
i'm going to close this 
i don't know whether non docker testing was done with the apps on the same machine or with different ip's etc.

**Comment by JoeStratton** [comment]
To answer your questions the containers are running on the same machine and IP address. I am happy to provide anything else if you want it. Otherwise good luck in the dev process!

**Comment by JoeStratton** [comment]
I know you don't want anyone posting issues here, but just an update that the application works outside of this container for me.
I also confirmed its only broken with NZBHydra, if I used the indexers directly it works.

**Comment by CHBMB** [comment]
@JoeStratton It's not that we don't want issues posting, just wanted to make it clear that it's not been released that's all.
